### ISSUE TITLE
Web site wording updates

### ISSUE THREAD

**Issue by adamdmharvey** [dxc-technology/OSSRank#130]
Opening this issue to record an effort to perform minor wording updates to the web site.  I found the site and thought it was extremely useful, especially because I've done exactly the site describes manually and could use the auto-ranking features.

Wording updates to be made include, but aren't limited to:
* Minor typos
* Sentence updates to the Taxonomy page
* Minor branding updates (a few places referring to CSC, change to DXC)

I don't have the ability to perform a full test (app engine, etc), and without a full CI/CD pipeline implemented, my PR won't be fully tested.  However, the wording updates are quite small and help improve the readability so hope they can be accepted.

**Comment by fsiddiqi** [comment]
Adam - thanks for the review and updates!  
The verbiage updates look safe.  I'll try to test and merge them over the weekend.

CI/CD pipeline is another planned enhancement, but we're doing manual deploys for now.

Let any of us know if you're interested in contributing further.

Faisal

**Comment by fsiddiqi** [comment]
@adamdmharvey updates deployed to http://ossrank.appspot.com/
Thanks

fs
